### ISSUE TITLE
Integrated mods - Checklist only

### ISSUE THREAD

**Issue by satyrlord** [StellarisPlus/stellarisplus#10]
- [ ] Stellaris + Event Module
- [ ] Stellaris + Buildings and resources Module
- [ ] Stellaris + Extra Technologies Module
