### ISSUE TITLE
Integrated mods checklist ONLY

### ISSUE THREAD

**Issue by satyrlord** [StellarisPlus/stellarisplus#3]
**Saturday, 4th of June**
- [x] Alpha Centauri Factions by Elothan http://steamcommunity.com/sharedfiles/filedetails/?id=687677693
- [x] Colonize Unlimited© by @Thomahawk2k & @dosaki http://steamcommunity.com/sharedfiles/filedetails/?id=682582076
- [x] 2D Galaxy by dskod1 http://steamcommunity.com/sharedfiles/filedetails/?id=681827490
- [x] Totalitarian Human Portraits by Ulmont http://steamcommunity.com/sharedfiles/filedetails/?id=683756022
- [x] Flags : Emblems & Backgrounds by swefpifh http://steamcommunity.com/sharedfiles/filedetails/?id=682165224
- [x] Cybrxkhan's Assortment of Namelists for Stellaris  http://steamcommunity.com/sharedfiles/filedetails/?id=682691478
- [x] Better Empire Names by Galle http://steamcommunity.com/sharedfiles/filedetails/?id=684475224
- [x] Galaxies Unlimited 1.0.2 by Langor http://steamcommunity.com/sharedfiles/filedetails/?id=682835797
- [x] Remove Aura Graphics by Chondrite http://steamcommunity.com/sharedfiles/filedetails/?id=683121431
- [x] Remove stranded foreign stations by Mysterius http://steamcommunity.com/sharedfiles/filedetails/?id=684509976
- [x] Enhanced AI by Anex http://steamcommunity.com/sharedfiles/filedetails/?id=692253918
- [x] Sol+ by Pascale http://steamcommunity.com/sharedfiles/filedetails/?id=682438556
- [x] Complete Colors by Delincious http://steamcommunity.com/sharedfiles/filedetails/?id=688576380
- [x] Increase Capital World Size Edict by Averax http://steamcommunity.com/sharedfiles/filedetails/?id=696195892
- [x] Arachnoid Pack Variations by Delincious http://steamcommunity.com/sharedfiles/filedetails/?id=691223396.
- [x] Creatures of the Void Variations by Delincious http://steamcommunity.com/sharedfiles/filedetails/?id=691223586
- [x] Avian Variations by Delincious http://steamcommunity.com/sharedfiles/filedetails/?id=693810942

**Sunday, 5th of June**
- [x] Change Capital Planet by Averax http://steamcommunity.com/sharedfiles/filedetails/?id=695883812
- [x] Advanced Tech Tooltips by Donkelton http://steamcommunity.com/sharedfiles/filedetails/?id=693097697
- [ ] Fixed vassal opinions by Lupin-\test\ http://steamcommunity.com/sharedfiles/filedetails/?id=683277624
- [x] Extended Traits by r-M http://steamcommunity.com/sharedfiles/filedetails/?id=681816257

**Saturday, 18th of June**
- [x] Color coded pop status icons by ParasiteX http://steamcommunity.com/sharedfiles/filedetails/?id=701739734
- [x] Nights on Planets by Flying Stationer http://steamcommunity.com/sharedfiles/filedetails/?id=696905076
- [x] Space Fox Dimorphism by artifex http://steamcommunity.com/sharedfiles/filedetails/?id=684337484
- [ ] Auto improve buildings by had http://steamcommunity.com/sharedfiles/filedetails/?id=691008512
- [x] Alien Suns by S.C.Watson http://steamcommunity.com/sharedfiles/filedetails/?id=689601294

**Saturday, 02nd of July**
- [x] Starfleet names (Star Trek) by Camulorix http://steamcommunity.com/sharedfiles/filedetails/?id=682447437
- [x] Rule, Britannia! Molluscoid clothes by Ofaloaf http://steamcommunity.com/sharedfiles/filedetails/?id=687743968
- [x] Rule, Britannia! British names by Ofaloaf http://steamcommunity.com/sharedfiles/filedetails/?id=688270686
- [x] National Emblem Pack by Swiss Knight http://steamcommunity.com/sharedfiles/filedetails/?id=681802702
- [x] Star Trek Emblem Pack by Swiss Knight http://steamcommunity.com/sharedfiles/filedetails/?id=682319439

**Saturday, 16th of July**
- [x] Planetary Rally Points by Zednosius http://steamcommunity.com/sharedfiles/filedetails/?id=693310104

**Tuesday, 9th of August**
- [x] Ripple Ping by Armakoir http://steamcommunity.com/sharedfiles/filedetails/?id=689794111

**Comment by satyrlord** [comment]
4c4c624a17fd0c21b44379b7803530b3caf0b815

**Comment by dosaki** [comment]
Good job!

**Comment by satyrlord** [comment]
Changed list of integrated mods to:

- 2D Galaxy by dskod1 http://steamcommunity.com/sharedfiles/filedetails/?id=681827490 
- Better Zoom by Rathwill http://steamcommunity.com/sharedfiles/filedetails/?id=687448131 
- Color coded pop status icons by ParasiteX http://steamcommunity.com/sharedfiles/filedetails/?id=701739734 
- Complete Colors by Delincious http://steamcommunity.com/sharedfiles/filedetails/?id=688576380 
- Cybrxkhan's Assortment of Namelists for Stellarishttp://steamcommunity.com/sharedfiles/filedetails/?id=682691478 
- Enhanced AI by Anex http://steamcommunity.com/sharedfiles/filedetails/?id=692253918 
- Expanded Plantoid Namelists by Shark that walks like a manhttp://steamcommunity.com/sharedfiles/filedetails/?id=739109368 
- Flags : Emblems & Backgrounds by swefpifh http://steamcommunity.com/sharedfiles/filedetails/?id=682165224 
- Megastructures by Nutsoman http://steamcommunity.com/sharedfiles/filedetails/?id=719712462 
- More AI Personalities by cybrxkhan http://steamcommunity.com/sharedfiles/filedetails/?id=701432146 
- More Tilesets by Sam http://steamcommunity.com/sharedfiles/filedetails/?id=804293993 
- National Emblem Pack by Swiss Knight http://steamcommunity.com/sharedfiles/filedetails/?id=681802702 
- Remove stranded foreign stations by Mysteriushttp://steamcommunity.com/sharedfiles/filedetails/?id=684509976 
- Ripple Ping by Armakoir http://steamcommunity.com/sharedfiles/filedetails/?id=689794111 
- Star Trek Emblem Pack by Swiss Knight http://steamcommunity.com/sharedfiles/filedetails/?id=682319439 
- Starfleet names (Star Trek) by Camulorix http://steamcommunity.com/sharedfiles/filedetails/?id=682447437 
- Subdued Borders by EvilVictor http://steamcommunity.com/sharedfiles/filedetails/?id=695602001
